### ISSUE TITLE
Не привязывай так конкретно имена к стилям

### ISSUE THREAD

**Issue by yuchiko** [KapSSe/Jwood.github.io#3]
`scroll_down_flex`
А, если ты передумаешь и поймешь, что тебе и display:block хватит, ты будешь переименовывать ? Назови `scroll-down` и не привязывайся к реализации

В таких случаях как, например, ты будешь делать `table`
Допустим у тебя есть table класс, он делает красивую табличку, но ты знаешь, что у тебя есть еще табличка, которая должна быть гибкой и мобильной. Окей! ты называешь `table--responsive` и юзаешь нужные тебе стили, чтобы смотрелось красиво. Можешь флексом, можешь дисплеями переделать, но главное, что ты передал логику в названии, а не обьяснение на какой технологии ты запланировал когда-то это сделать

**Comment by KapSSe** [comment]
1. Понял в чем логика, убрал из названий классов тип используемой технологии.
2. Использовал в навигации вместо flex'а - `display:inline-block`.
