### ISSUE TITLE
Не гибко

### ISSUE THREAD

**Issue by yuchiko** [KapSSe/Jwood.github.io#4]
`horizontal_ruler_grey`
`horizontal_ruler`

отличие в цвете, но ты создал два правила, которые друг друга полностью повторяют, почему не сделать одно общее, а потом уточнять дополнительным?

```
.hr {} /* общее */
.hr--grey {} /* серый модификатор по БЭМ*/
.about .hr {} /* без БЭМ можно и вот так, если это частный случай */
```

**Comment by KapSSe** [comment]
1. Удалил классы `horizontal_ruler_grey`  `horizontal_ruler`, понял ошибку.
2. Удалил `<hr>` сделал через `::after`.
