### ISSUE TITLE
Если назвал помидором, оставайся помидором

### ISSUE THREAD

**Issue by yuchiko** [KapSSe/Jwood.github.io#5]
`to_uppercase`
Ты называешь класс, который для меня говорит, что он делает буквы прописными, но потом я вижу, что он еще и убирает подчеркивание...не надо так :(

Плюс у тебя есть повторения в твоем `main.css`
http://joxi.ru/BA0RKWphJdnV4m

по сути, ты тут применяешь Atomic CSS, но грубо и через чур детально, у них там под каждый пчих создается класс, но в сокращенной манере. Например твоя штука выглядела бы так
`.tt-u .td-n`

Вот [статья](https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/), но я не фанат такого 
```
.Bfc {
    overflow: hidden;
    zoom: 1;
}
.M-10 {
    margin: 10px;
}
.Fl-start {
    float: left;
}
.Mend-10 {
    margin-right: 10px;
}
.Fz-s {
    font-size: smaller;
}
```

**Comment by KapSSe** [comment]
1. `to_uppercase` убрал повторы.
2. `to_uppercase` теперь делает только то, для чего задумывался.
